spring:
  application:
    name: "market"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/market
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8888
